const ASIDE_ENTITY = '[ASIDE]';

export const ADD_PRODUCT = `${ASIDE_ENTITY} ADD_PRODUCT`;
export const CLEAR_ASIDE = `${ASIDE_ENTITY} CLEAR_ASIDE`;
export const ADD_QUANTITY = `${ASIDE_ENTITY} ADD_QUANTITY`;
export const SUB_QUANTITY = `${ASIDE_ENTITY} SUB_QUANTITY`;
export const UPDATE_QUANTITY = `${ASIDE_ENTITY} UPDATE_QUANTITY`;
export const REMOVE_PRODUCT = `${ASIDE_ENTITY} REMOVE_PRODUCT`;
export const SET_ASIDE_DATA = `${ASIDE_ENTITY} SET_ASIDE_DATA`;
export const SET_TOTAL = `${ASIDE_ENTITY} SET_TOTAL`;
export const UPDATE_PERCENT = `${ASIDE_ENTITY} UPDATE_PERCENT`;
