export const CHANGE_POPUP_STATUS = 'CHANGE_POPUP_STATUS';
export const MOBILE_ACCOUNT_STATUS = 'MOBILE_ACCOUNT_STATUS';
export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_USER = 'UPDATE_USER';
