name: React.js CI
on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ master ]


jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm cache clean --force
      - run: npm i
      - run: npm run build